version: '3'
services:
  redis:
    image: redis:alpine
    container_name: note-app-blacklisted-jwts-redis
    ports:
    - '127.0.0.1:6379:6379'
  postgres:
    image: postgres:alpine
    container_name: note-app-postgres
    environment:
      POSTGRES_PASSWORD: 'supersecret'
      POSTGRES_DB: 'notes-app'
    ports:
    - '127.0.0.1:5432:5432'
